global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:8000"]

  - job_name: "kitchen-service"
    static_configs:
      - targets: ["kitchen-service:8000"]

  - job_name: "inventory-service"
    static_configs:
      - targets: ["inventory-service:8000"]
